### PR TITLE
Fix `writeZone` in flake-mode

### LINKED ISSUE #4: writeZone does not work when importing as flake
`writeZone` relies on `pkgs.writeTextFile`, which is only available when the full `nixpkgs` is instantiated (`import "${nixpkgs}" { system = "some-system"; }`). It's simple enough a wrapper that I can just call `writeTextFile` myself, but I guess it should be documented somewhere along with `writeZone` itself.

### PR DESCRIPTION
**Pull request by kirelagin**
See the commit descriptions for details.

Fixes #4.
Obsoletes #10.

### CODE REVIEW

**Comment by kirelagin** [comment]
@AluisioASG @ncfavier, what do you think?

**Comment by ncfavier** [comment]
Looks good to me.

**Comment by AluisioASG** [comment]
I've tested it and it works for me.

**Comment by kirelagin** [comment]
Thank you both for your help! I am going to deal with other open PRs and tag v1.0.

**Pull request merged**
